import turtle as logo

logo.bgcolor('black')
logo.setpos(0, -250)
logo.pensize(8)
logo.fillcolor('black')
logo.begin_fill()
logo.pencolor('gray')
logo.circle(250)
logo.end_fill()
logo.pensize(3)
logo.up()
logo.setpos(0, -150)
logo.down()
logo.fillcolor('white')
logo.begin_fill()
logo.circle(150)
logo.end_fill()

logo.fillcolor('blue')
logo.begin_fill()
logo.circle(150, 90)
logo.left(90)
logo.pensize(2)
logo.pencolor('black')
logo.forward(150)
logo.left(90)
logo.forward(150)
logo.end_fill()
logo.up()
logo.setpos(-150, 0)
logo.down()
logo.begin_fill()
logo.pensize(3)
logo.pencolor('gray')
logo.circle(150, -90)
logo.left(90)
logo.pensize(2)
logo.pencolor('black')
logo.forward(150)
logo.right(90)
logo.forward(150)
logo.end_fill()
logo.pensize(12)
logo.pencolor('white')
logo.up()
logo.setpos(0, 0)
logo.right(35)
logo.forward(165)
logo.right(5.2)
logo.down()
logo.forward(64)
logo.right(90)
logo.forward(35)
logo.circle(-16, 180)
logo.forward(35)
logo.right(180)
logo.forward(35)
logo.circle(-16, 180)
logo.forward(35)
logo.up()
logo.setpos(-32, 165)
logo.setheading(90)
logo.down()
logo.forward(62)
logo.setpos(0, 180)
logo.setpos(32, 227)
logo.right(180)
logo.forward(62)
logo.up()
logo.setpos(0, 0)
logo.setheading(52)
logo.forward(228)
logo.down()
logo.right(170)
logo.forward(65)
logo.left(142)
logo.forward(50)
logo.right(142)
logo.forward(50)
logo.left(142)
logo.forward(65)
logo.hideturtle()
logo.done()
