import turtle as logo
from time import sleep

logo.getscreen()
logo.bgcolor('white')
logo = logo.Turtle()
logo.getscreen().colormode(255)
r = 120
logo.setheading(-150)
logo.up()
logo.color(223, 35, 35)  
logo.begin_fill()
logo.fd(r)
logo.down()
logo.right(90)
logo.circle(-r, 120)
logo.fd(r * 3 ** .5)
logo.left(120)
logo.circle(2 * r, 120)
logo.left(60)
logo.fd(r * 3 ** .5)
logo.end_fill()
logo.left(180)
logo.color(75, 183, 75) 
logo.begin_fill()
logo.fd(r * 3 ** .5)
logo.left(120)
logo.circle(2 * r, 120)
logo.left(60)
logo.fd(r * 3 ** .5)
logo.left(180)
logo.circle(-r, 120)
logo.end_fill()
logo.left(180)
logo.circle(r, 120)
logo.color(252, 216, 9) 
logo.begin_fill()
logo.circle(r, 120)
logo.right(180)
logo.fd(r * 3 ** .5)
logo.right(60)
logo.circle(-2 * r, 120)
logo.right(120)
logo.fd(r * 3 ** .5)
logo.end_fill()
logo.up()
logo.left(98)
logo.fd(r / 20)
logo.setheading(60)
logo.color(86, 146, 195) 
logo.down()
logo.begin_fill()
logo.circle(logo.distance(0, 0))
logo.end_fill()
logo.ht()
logo.penup()
logo.goto(-110, -300)
logo.color('black')
logo.pendown()
logo.write("Google Chrome",
     font=("Lucida Handwriting", 20, "bold"))
logo.getscreen().exitonclick()
