import turtle as logo

logo.Screen().bgcolor("Black")
logo.speed(2)  # Set the turtle speed to 2 (slower)
logo.begin_fill()
logo.fillcolor('#1DB954')
logo.pencolor("#1DB954")
logo.pensize(0)
logo.circle(100)
logo.end_fill()
logo.penup()
logo.goto(40,50)
logo.pendown()
logo.left(150)
logo.forward(0)
logo.pensize(15)
logo.pencolor('black')
logo.circle(80,60)
logo.penup()

logo.goto(50,85)
logo.pendown()
logo.pensize(17)
logo.right(60)
logo.forward(0)
logo.circle(100,60)

logo.penup()
logo.goto(60,120)
logo.pendown()
logo.pensize(20)
logo.right(60)
logo.forward(0)
logo.circle(120,60)

logo.done()