


import turtle as kreggscode
kreggscode_screen = kreggscode.Screen()
kreggscode_screen.bgcolor('blue')
def kreggscode2(value):
    for i in range(value):
        kreggscode.right(1)
        kreggscode.forward(1)
kreggscode.penup()
kreggscode.setposition(0, 43)
kreggscode.pendown()
kreggscode.begin_fill()
kreggscode.pencolor('black')
kreggscode.fillcolor('red')
kreggscode.pensize(3)
kreggscode.forward(81.5)
kreggscode.right(49.4)
kreggscode.forward(58)
kreggscode.right(81.42)
kreggscode.forward(182)
kreggscode.right(98.36)
kreggscode.forward(182)
kreggscode.right(81.42)
kreggscode.forward(58)
kreggscode.right(49.4)
kreggscode.forward(81.5)
kreggscode.end_fill()
kreggscode.penup()

kreggscode.setposition(38, 32)
kreggscode.pendown()
kreggscode.begin_fill()
kreggscode.fillcolor('gold')
kreggscode.forward(13)
kreggscode.right(120)
kreggscode.forward(13)
kreggscode.right(120)
kreggscode.forward(13)
kreggscode.end_fill()
kreggscode.penup()

kreggscode.setposition(81.5, 25)
kreggscode.pendown()
kreggscode.begin_fill()
kreggscode.right(210)
kreggscode.forward(25)
kreggscode.right(90)
kreggscode.forward(38)
kreggscode.right(45)
kreggscode.circle(82, 90)
kreggscode.left(90)
kreggscode.circle(82, 60)
kreggscode2(61)
kreggscode.left(90)
kreggscode.forward(57)
kreggscode.left(90)
kreggscode.forward(32)
kreggscode.end_fill()
kreggscode.penup()
kreggscode.home()

kreggscode.setposition(-69, -38)
kreggscode.pendown()
kreggscode.begin_fill()
kreggscode2(20)
kreggscode.forward(33)
kreggscode.left(10)
kreggscode.circle(82, 20)
kreggscode2(30)
kreggscode.forward(10)
kreggscode.right(110)
kreggscode2(40)
kreggscode.right(10)
kreggscode.circle(50, 10)
kreggscode2(45)
kreggscode.right(5)
kreggscode.forward(45)
kreggscode.end_fill()
kreggscode.penup()
kreggscode.home()

kreggscode.setposition(20, -100)
kreggscode.pendown()
kreggscode.begin_fill()
kreggscode.right(135)
kreggscode.forward(27)
kreggscode.right(90)
kreggscode.forward(27)
kreggscode.right(135)
kreggscode.forward(38.18)
kreggscode.end_fill()
kreggscode.penup()
kreggscode.home()

kreggscode.setposition(-57, 32)
kreggscode.pendown()
kreggscode.begin_fill()
kreggscode.right(180)
kreggscode.forward(18)
kreggscode.left(45)
kreggscode.forward(44)
kreggscode.left(80)
kreggscode.forward(15)
kreggscode.left(130)
kreggscode2(40)
kreggscode.forward(20)
kreggscode.end_fill()

kreggscode.hideturtle()
kreggscode.exitonclick()
